#!/usr/bin/env python3
"""Embed binary or text files as C byte arrays.

usage: embed.py OUTPUT.c INPUT...

Each input becomes `const unsigned char <name>[]` plus `<name>_len`, where
<name> is the file name with every non-alphanumeric character replaced by
an underscore.  A trailing NUL is appended (not counted in _len) so text
inputs can also be used as C strings.
"""
import re
import sys

out = sys.argv[1]
with open(out, 'w') as f:
    f.write('/* Generated by tools/embed.py - do not edit. */\n\n')
    for path in sys.argv[2:]:
        name = re.sub(r'[^A-Za-z0-9]', '_', path.replace('\\', '/').split('/')[-1])
        data = open(path, 'rb').read()
        f.write(f'const unsigned int {name}_len = {len(data)}u;\n')
        f.write(f'const unsigned char {name}[] = {{\n')
        for i in range(0, len(data), 16):
            f.write('  ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 16]) + ',\n')
        f.write('  0x00\n};\n\n')
